# @file    moccasin_logo.py
# @brief   Embedded icon for use in the "About" panel
# @author  Michael Hucka
#
# <!---------------------------------------------------------------------------
# This software is part of MOCCASIN, the Model ODE Converter for Creating
# Automated SBML INteroperability. Visit https://github.com/sbmlteam/moccasin/.
#
# Copyright (C) 2014-2018 jointly by the following organizations:
#  1. California Institute of Technology, Pasadena, CA, USA
#  2. Icahn School of Medicine at Mount Sinai, New York, NY, USA
#  3. Boston University, Boston, MA, USA
#
# This is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation.  A copy of the license agreement is provided in the
# file named "COPYING.txt" included with this software distribution and also
# available online at https://github.com/sbmlteam/moccasin/.
# ------------------------------------------------------------------------- -->

# The rest of this file was generated by using the img2py.py program that
# is provided with wxPython 4.0, with the following command line:
#
#   img2py -f -i -n MoccasinLogo ../../docs/project/logo/moccasin_logo_20151002/logo_64.png moccasin_logo.py
#
# The only changes to the output were to add the file header and this
# explanatory comment.

from wx.lib.embeddedimage import PyEmbeddedImage

MoccasinLogo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAFHtJREFUeNrsW3lwXeV1'
    b'/93l7Yue9CTLkmxLjhfM4oKxC2EIIWZaTIc2k6aG4qmhy2SYTiZTptAkTSgdUlqalkkKgxOS'
    b'AE3SsLRloJOYtRAwNglms+VNxrI227K16z09vX25t+d899733pXee3qWxfSP9sHxXb67fOf3'
    b'nXO+3znfFfB//CdVOrlr12NvNYWb6r5Nqvm08+uOtMAzdN2+PzIy0n3P3X/xl4t9o1rp5Lp1'
    b'az931dVXze+eVN7BCiBUaJMqYldDUUmuiaNu/sPKa7qEl17cfUGQy9VeIkGvgL4+tyvzOja3'
    b'Ta9jJOtrsAPKAEqSfsFWJyygta1jXoMm0NHpP/sbNE2HLEu1h0iy7ZTtWQcmxDoqWIJunq/+'
    b'Dm7STd0v1OtUVv7A1/SH6b1XWCcTQ/+I7HRgMeFjSeOBcsMP4fEHqr5eWoIgqJqgX+H3Stcr'
    b'ivHIBvQC8f/d6ByLa5g6dxqd6y+tCrQuLRUAvOMGHI76b+ybdCKeMULIFR1pjM6qGJE20kOC'
    b'QHIYmxr7bdfOBq4xOj7TgyuWTSz8grgRc1iquYO0BJZWBEAi5SWXXv8Irb0LG7feiUOHDqGv'
    b'/wG4t30Pl7W2Fts/2vfv2DD5t+iVbkbXjgfQ6fcX2/a+8gSuV74P5GMLzHmLnMcXMwtIDo0A'
    b'qF+sN/tJsfCNP0ErKc9gSKZSv3HdbdjjfBCXfeFfxHH/iYPFl17zO1/CAe13az+/PCh+gq4m'
    b'l9uC5NTrFuvONWvWCKWPP3cjLh3/Inpoa4Fw483bMXb2JCKv34Bw763o+a/txbZC2x/Ufr7N'
    b'ErRPDISSBaiaYQX1ilTq0tD+f8KVK08gEMhj/fJxDBwpkZPp976M9W1jaGvJosPdjfGBN0t6'
    b'ha+q+vzz5QcXDgDtSUr9Uu586sxrxfMBfwGJRGkKkXNnim1tzTmMjY/Z3l71+ajED5YehBIV'
    b'FqxqkS+QUP3eGm1SrfuqREUmZtInAkCdUbdqtNaXuK1aE8eDBfKFRQGga5KQub+T482I6Z24'
    b'KHgQfo9WsXfGvfKFt1XCpxJdrsyhL3AWyNMDc3Y5cGY9Qlv34JLPP4/3tW/b2mzuWJAW1aYX'
    b'MO+dRVnIFZYoHpQsIEepT8b+4nzzdjHP888bvgj6ZFl0UkrXGveefxtyir2ton+wslLlpGkJ'
    b'HKEEANHauZOPPPUCdfI2QW+lmePQUmUv9JYpScAtSdscBReMj0vAD4oAaBmSgr0zl3sG0P3j'
    b'26D7OtCe/hW0QKk9cPoRHD38qNhfG85BS9bXJvU9Ktp43PX2dM1R1Mty6apuf4GuUAQgk2TX'
    b'm/+w9cpJIH1S7CdnS+fbXYSYyzzIUlu2vrb1gVRxv/x5C08z0lLGPjsAEwk8NxrThrnWIdLh'
    b'NVt3tLQ0V007pEVkJ9IiUhiP11dnEeUCABgbOYtt3+94jPYft07+65M7d6zbssUsOkgV+yzN'
    b'P1G2kZaknmirPJWBsOQWQCBohrFaL1YgKwqOxo7j2eEX8OClf3NeIMhGCJs/59pKaZIBSpES'
    b'6jgdyyOZL9X5mt0knvmMqNwKZpyNoW1P9f5JPl9Ynctr0HL5aCFf6B548PfeNvU6/6pw+e8I'
    b'RX+cn6sWi6rV6omGNRgVvZ6pDPYNp3FgPIc0J5kysbyya5o9Em7pcmBzq9tmBQfGs3j64wTG'
    b'tXVXOB3aj2WRzBSIztCbaQBX3/vSTGcu//N8cvZbZ3ftHGBLXxQAojiTT8Cv+uZUN6szc704'
    b'xnYQWDnZHLqhaA4/7ZlFb6QAVaXzimxsSfkSCDTCxBafGODsM00geGn0NfykN41fjWbErKU6'
    b'FOMeSRLbrLivwG9toH/v0L3BOzruem5X8+jAt449vHOyrrJ4JSsoMi99Ph2ppL0+z/xlMaJ8'
    b'/q3TSfzduxH0RQtwkAIKiWqJUy3uKw5jn6/pn06I5zx/OocPIhqdU+FwGtewpOJpxCNxpGaS'
    b'0PIF8UzZIUNR+RrnVxzNnXs7b7pz3dwKuFpPGvLe9Ef4dNPmCqXvKpZgtluldYlM0vJZVv6H'
    b'h2JwmoqLDircUcMKlikZrPYUkKWceDSrYAoeOJHHpZRm98U17J2CuEfUCgsypkancHBvDzKp'
    b'bPFZEok74EHD8hD8Qa+4VtHcF/uv/sNXKJHahpEf9NcEwBrsZa4Wsd0f+RB34c6aBcpaRXzr'
    b'jsFoFo91x+CyFCdRxVbGJkcEW1tlrFrWCKfLbaQR+TwmUjkouQyagmH8G8U0vpY7yPFkZGgU'
    b'+189JKzG5XFCJ0vIU3ueAEhyMWYsimAyg47mIGQ67/T617h/85bvtXbvvpliQqGmC7Cyy1wG'
    b'F0gXkvjlxD776lAdriCJSC8XGd1D70fh4NG2hDrlUXX8aWgEd1zahLUr2+Fye4oBUHU40Nbg'
    b'Q2tzGDnZgR5ilGwlLAWK+Afe7hGKqyQZrwspH7EvvwcBGvWWkA/LQ3546NpEIl18p8Pl3ea9'
    b'/Qd/brmCvFBY3xi8GC6KvM+eeQGJfPL8QCj7vXkqiemMJgKdMHfe0lR7e9MkNq/rIkU8VZfK'
    b'+Knn0poRRM0gOTUaEYFPdzuQJAAUnxvLSPGVpHh7ox8tjT6ESZpp3+d2Gl7JADCA3uA36NC9'
    b'IACs52rfKnFRLDcuOMHc33h6QoBTCQS5zF1eHkyKETCUIOVJrvVEsLGrXXAOy0wqUnuK/ENp'
    b'nkFgzA4ksxEKdi4H0qScz+8mS/EiTOIPeeEjCZAETQkQKGwpxnslOFRHh+PGez67AABGT25o'
    b'uQ4pSkebVQ0vjrw6zxXGMpN45vTzlfmCuUYYz+RxZrYglJYpHZZMM/7tVV6K5K552U8lEHyE'
    b'Udghwa9IAgiHl8ze6YCXTH8Zmb0/4IY3SIGPJCTEixAB0iC2HrHPVidRH1R6gBJavp3cQFpw'
    b'Glzt7UTY2YwcgdDuKOCJoZ8JhlgEwezsE4M/m2cFliJDMznTdA3f5m2nM0sjFpjvSXrlJM9D'
    b'PW0iAFiCqoRlK5qgkPk3k997hbgRJEvwk/gYDBKPufXyORIXWQxbj8J98AR5qcolL0ztgM+3'
    b'3YQYkY6AoiMsz+K+nn/AI30/wnhmUlzTTFF9KjOMX5x71QaCsbRFbpLMC3cQwU22AMgIi6g8'
    b'8c43Af4WoMFUvoFkRbMfbWE/vOQCLrIGH4mHxE1guMkq+Jwlbp8hGs9iFmnSdc7IZbUefstu'
    b'wP4fL8wiTFG7keRIdB+5w97iVLmZzPBxsoLLGi7Gp3ydttnEq6IY2SVjYR8TFIMMTl8hwTEp'
    b'b3klKKnJ8CpGY4Ha08QQr9ryKZw4fg5uGlk3WYPTFMEOOeqbXESje/MFDYWCVkzMZOk8mKBP'
    b'8eBLnTsxlqfph+2Gbl7vlnBdUEWHGsUKmodDNJ9fFfDhm0f/HgOJU/b7HbJZAi/xglNZJ2bT'
    b'WduI6xWqIQxSLC8JquWiXjslS8glmnzoWt8mSJUqWKMqZhiW5WTc6ylwrCHfCdL7pyfjtqxU'
    b'ymfOcdVPrpfPsBVsatyCszmljEaSL9LLV7hU0d8uN01FFCwtEKxYsKHRYU+XJU49ZeydpCs0'
    b'vSYInBz2J1XDbMXMUiZ03Bj2oaUtZGOB7CYraYBWkfIsialZxKJJlH9UoM+Ov8dVSbn+mryO'
    b'u9bcCVVpwVixaqubSpof7dD2moYgOgl9BuHITI9RB1VVXNuqloKbefmbUQfepKSG0teK756m'
    b'9xyeVZCk+FOgGwoiFkC4AG8182Ke4rwNbrG6pbGp5wqYzRB1nkzi54fH0T8yW4KX/y/kktkT'
    b'+54lNqhXLMn+0c7b72/vaJ9XAnASG9tIPv7i+H4ywRxNSexnPD/bt6vcfgpYXjw+9KKxUtxw'
    b'CVb6JPx6NAdNLnEBDkj9WQeOxWmqzLNSGmbJ3PuSMk4kZAykVWR1o1ibo3+ypHWaJEkIxFk0'
    b'w0WEaIY15bN5xBJZnJ5O41QkjXSWUuQCCTFHZo+cKGVG+3bN7HnimUR8tgYA7e2oVAxqdDSQ'
    b'hPDqxEfCJxvUSiAoFBxDlMLIeGP8AwqKXdgQWgm/lCerQJHRSSYICerGUEbGwYSCI6T4ZFYW'
    b'QU7kA6YbZETgM5RPkCkQrQARS3MqNpTn/EArWMLK6iLw5UjypLhGAORiU8dGnvzyH9PopxbO'
    b'BqtUoDgeMCEaSnxM/l9ergJ1roDueBT9qXO4MnQlntz811juWSbaPrvSx7QI/3nOnCLNUaM5'
    b'yYj4rCgdxwoG7Dm6xkVtgvJSW1ZnAEj5PIOgo+R9etEKNL3s2ew2FjDW+WzqbS4k1VEQqfyV'
    b'V4ISowdPPILB+HFs8hm3zxDCM2RqZzJJ5ODCpylY3nPRF9HqbrFnj7R//Uo/mpwGCLM0Pclm'
    b'B2We9jQjyrFyPOopjd0OooRuuIEuzqWLpm8qJp6hiefoYmvsa8V9rQxsR7Y8xKl10IBimetY'
    b'7GM82PuwSIp81LGjNBzRQl5kjRuDl+CGtotJ+c3wqd6y5d9SiWySej9JSc3qRg/uDabx7lgM'
    b'H6cdGND81EodZYqsGffxigGbuBXtOdhqevmHkiUL0kyJTMSQSWaErzPwHmKHbAEFzbqWHugK'
    b'3kJP+LpVA1XPo8gnNjtW/D7xAm+RAK0m0sPHleoE5WfiFMW+8U6E4oKCAM0S27sUbF3dhK30'
    b'1Fwmg8GUjGECqD+hY0D3QTJjgEbP1WzUujT6QnmyvqP7ezF0/CySs+myeiLPDi50XrYSTgJC'
    b'xASODZA6/Dt3fRNPfeV+rhPWLIjMBeGy4AYa6Q0V1ZxbLLEBwlPeUBIz6QJcRGcTNL09NaRj'
    b'S+MMfMGQSIU3eCTwk2+gGDISi+GVaSdO5tx2FM3U2PLvbCqLt55/DzPTccH+mAYzDzA/IxXX'
    b'DB09g7a1y4kSuwQIOQIh6268mx7zXU5y5VqpcCVWoNdkDNXrAe+eSYqpyJqSAnpGlN+tAGbd'
    b'y6lxR2MQf9blwOXenOi0LkbPlHxp+9YL7yMRS5HibsgkWZIUUfJUwEviMYSOz47HDH5AkqH3'
    b'k2sF0jfdt4OLIirO52f3iAWXroq1Qmo4PJoWNUBjLaCADd48jUp4jvWUnsxA7FghYbo/J9zD'
    b'5vu0Pf5hvyiEqjSyac7ySLyUB/iIDjtVowDLATJLQCWyOSSSRuzLEAhZAkGT1KvpxI/UhQoi'
    b'3K/RkRHRsXQ6jVBjI6LRCBp5G4lQEuIunY9EaRvCTDSKcLgZAWKFFvtkdib2Tf9spgyp3E0q'
    b'gcA84QttMh7q1UwSZ1oLucC5wXFIlAmmmAUSCGFOibk85lQFLTYA4IUSDSEiR+l0DknqQ5qt'
    b'kIOkK7SJnuRY0AJ0ff56PfRqxl7iD/octxF0V7JWCzgoKvapVrdNHMXfCr+KoJTCdLZEemKR'
    b'BDKsDCkeJDNv4dyfzN9NALgpL1FNAPj6HF+XySFH96RSGWSoH+xSaj7vECy9HstvXd5m61go'
    b'1Cj6HQqFbK7Ax9zA7aXVH0PHS8IqeqbyxWzw0FgaO2la4pJ5LSsQi7U0N45lteIMkKEskqtB'
    b'HgKgRRRAPKLg4aNjp8u0AFkyqDEB4CYAzo3PIE37PBAKvVdJTn/I9d66iNDi4gF/4FDKvjob'
    b'nRQHMkWzOj6l4NTEDLpaG21PKH2OX3oyz+vM8S2QOLLopGgTKcyRn5UPkLi9TjgoFiiqXASA'
    b'Fc6TwpMzKYoHBcj0LJUsQE5FD/Hj1NoKGp0YHR0xviEo+nqk6PNuj7vCeY4NXJ4OIBAw4sD2'
    b'jSH8x+EIPGXc/dGP4vjnbUHKMBXbEtpcSxiJZZHNasUYwH7Oo+2joCcyQU+p+iNigGIUUJkA'
    b'ceD9+OApcpk8JGv0c9mk7+DLrw0RD5DrC/2LuyKbKX0ZsYLY38UtDuIANA3RaBZIjoxm8dDe'
    b'UTE1lv+FipXh8e/oRAZnZrJI0fWpDEtO7Lc1+cXc73LyEpkhqjkDrHTLuMinYIVHwekzUzg1'
    b'PEUZlTHyYvSnBnan0oN9CzNB0wqXUwzAPF8v+bw1ePbzKLmCec39v9WOW58ZQDyrw02j4yJ5'
    b'oy+J8cQ5/NVnWtAectuI1UAkhwf2TdDoaXYmyPc6ja5bCx6yKIYYRdNOr0yKFvDGB6ewt3tY'
    b'jLylvEqjj77Xv6MvRIXtf/my+HhQ5AYUD1aFfbj7M8tw3xsjlNgoJBpcZP4Hh5O447nTWBN2'
    b'49oun1hNGohksZ8yVkmys03d/HhQ7JNCURpZnhY55ZWTFFAJgJ4jEbxzfBQxmvvZ59nsHSYA'
    b'GP7w29rYkQPWcrlahwHMA8FOeKpqX2znHEQyvza5dVOryM7ufX2ECAmZsKKJ1RonyfHRBHrH'
    b'U2XfEKBkYXPyACsBihMdHo/G6Vm6IDgZzvlpqwvFdWEJiqX82Q8f1bp/+rC1LlhXNsjvPdxt'
    b'fOsfJYLTtXo1hgaHaNslthbx6exajVNDg+ik9lODgyIYzlAwtI7Xrlsv1vZX0fFtm9vgp5H6'
    b'+mtnMZuRBAAsqrVoYdXuJWt90YwLZkaomXl+nrYc4QW/N6kuU17JHHEGgJWnoJfC8Hvf0Q4/'
    b'/RApP7vg10ovvfyqvnnzlfMvqvA3KnbiIqHKJ0UliitLxT/7mojO4v7/PoPdJ5NGGVsoLwvl'
    b'iwDQ1qfquIYYYUfAYawTxjXsOZPBTIaB0AQYbGYSKyxEMxSnfWlmeJ9+9Ln79KneX5Pyubq+'
    b'6ZoLQC0Q5gEwf1MBBLlUnaXOTkzH8NKxCfxyII5oKo/DEQmXN+locCv43CoXtl3UhPbWZiI5'
    b'LnEb6ztJZv/isTE8/e6pZG/UwaU4LxdXZP4WID55UoqdfQdjPc/rQ3t4LS9W7ROZygC89Iq+'
    b'ecvm6hfXCUI1AEoLJPYPrjTy12wmhVw2K5Ihj4fX8xxFRjn3SzOOBb/YvXvfV7/6tR1csy17'
    b'EX9OEuEiUjXFa38gURc3XDgo6lJlllgtYrLSbq+fpPyLsxJDMBZkLRB0cxpUC6Tk2Qv+UrT8'
    b'NzAwuCcSidQw4gv9XE8ipugS6wU160iVv8IzJwROdPKUqY524/9/i//9jwADAESKk97h9rAa'
    b'AAAAAElFTkSuQmCC')
getMoccasinLogoData = MoccasinLogo.GetData
getMoccasinLogoImage = MoccasinLogo.GetImage
getMoccasinLogoBitmap = MoccasinLogo.GetBitmap
getMoccasinLogoIcon = MoccasinLogo.GetIcon

